name: Perf tool issue
on: [push]
jobs:
  test-perf-tool-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install perf
        run: sudo apt-get update && sudo apt-get install linux-tools-generic
      - name: Enable perf event paranoid flag
        run: sudo sysctl kernel.perf_event_paranoid=1
      - name: Set Kernel KPTR  Restriction
        run: sudo sysctl kernel.kptr_restrict=0
      - name: Run perf command with -a
        run:  sudo perf record -g -e cycles -a -o perf.data sleep 5
      - name: Run ls
        run: ls -la
      - name: View perf output
        run: sudo perf script -i perf.data
  test-perf-tool-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Install perf
        run: sudo apt-get install linux-tools-generic
      - name: Enable perf event paranoid flag
        run: sudo sysctl kernel.perf_event_paranoid=1
      - name: Set Kernel KPTR  Restriction
        run: sudo sysctl kernel.kptr_restrict=0
      - name: Run perf command with -a
        run:  sudo perf record -g -e cycles -a -o perf.data sleep 5
      - name: Run ls
        run: ls -la
      - name: View perf output
        run: sudo perf script -i perf.data
